library(shiny)
library(scales)
library(bslib)
library(DT)

assumptions_ui <- function(id) {
  ns <- NS(id)
  

             tabPanel(title = "Population Assumptions",
                      fluidPage(
                        sidebarLayout(
                          sidebarPanel(
                            h4("Set Adult Population:"),
                            numericInput(ns("adult_pop"),
                                         "Set Adult Population:",
                                         value = 10000,
                                         min = 0,
                                         step = 10000),
                            h4("Set the MASLD and MASH Prevalence:"),
                            sliderInput(ns("masld_prev"),
                                        "Set MASLD Prevalence:",
                                        value = 24,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("masld_prev_tol"),
                                        "Set MASLD Prevalence tolerance:",
                                        value = 5,
                                        min = 0,
                                        max = 25,
                                        step = 0.5,
                                        post = "%"),
                            sliderInput(ns("mash_prev"),
                                        "Set MASH Prevalence:",
                                        value = 4.5,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("mash_prev_tol"),
                                        "Set MASH Prevalence tolerance:",
                                        value = 1,
                                        min = 0,
                                        max = 10,
                                        step = 0.25,
                                        post = "%"),
                            br(),
                            h4("Set the Fibrosis Stage Assumptions"),
                            sliderInput(ns("F0_prop"),
                                        "Set proportion at stage F0:",
                                        value = 23,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("F1_prop"),
                                        "Set the proportion at stage F1:",
                                        value = 36,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("F2_prop"),
                                        "Set the proportion at stage F2:",
                                        value = 20,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("F3_prop"),
                                        "Set the proportion at stage F3:",
                                        value = 13,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("F4_prop"),
                                        "Set the proportion at stage F4:",
                                        value = 8,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            br(),
                            h4("Set the Prevalence rates of Obesity and Diabetes"),
                            sliderInput(ns("ob_prev"),
                                        "Prevalence of obesity within MASLD population:",
                                        value = 55,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("ob_prev_tol"),
                                        "Set the obesity prevalence tolerance:",
                                        value = 10,
                                        min = 0,
                                        max = 20,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("t2d_prev"),
                                        "Prevalence of Type 2 Diabetes within MASLD population",
                                        value = 30,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("t2d_prev_tol"),
                                        "Set the Type 2 Diabetes prevalence tolerance:",
                                        value = 12,
                                        min = 0,
                                        max = 25,
                                        step = 1,
                                        post = "%"),
                            br(),
                            h4("Set the diagnosis rates for each Fibrosis Stage:"),
                            sliderInput(ns("diag_f0"),
                                        "Set the diagnosis rate for F0:",
                                        value = 2,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("diag_f1"),
                                        "Set the diagnosis rate for F1:",
                                        value = 2,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("diag_f2"),
                                        "Set the diagnosis rate for F2:",
                                        value = 16.5,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("diag_f3"),
                                        "Set the diagnosis rate for F3:",
                                        value = 58.3,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            sliderInput(ns("diag_f4"),
                                        "Set the diagnosis rate for F4:",
                                        value = 100,
                                        min = 0,
                                        max = 100,
                                        step = 1,
                                        post = "%"),
                            br(),
                            h4("Download Assumptions"),
                            downloadButton(ns("download_assumptions"), "Download Assumptions")
                          ),
                          mainPanel(
                            h1("Population Assumptions"),
                            h3("Prevalence"),
                            p("Based on the input prevalence assumptions the total population with MASLD included in the model will be:"),
                            verbatimTextOutput(ns("masld_prev_summary")),
                            p("The tabs below show the simulated MASLD populations to be used within the model as either a histogram or table:"),
                            #plotOutput(ns("masld_pop_histogram")),
                            navset_tab(
                              nav_panel("Histogram", plotOutput(ns("masld_pop_histogram"))),
                              nav_panel("Table", DTOutput(ns("masld_pop_DT")))
                            ),
                            h3("MASH Prevalence"),
                            p("Based on the input prevalence assumptions the total population with MASH included in the model will be:"),
                            verbatimTextOutput(ns("mash_prev_summary")),
                            p("The tabs below show the simulated MASH populations to be used within the model as either a histogram or table:"),
                            navset_tab(
                              nav_panel("Histogram", plotOutput(ns("mash_pop_histogram"))),
                              nav_panel("Table", DTOutput(ns("mash_pop_DT")))
                            )
                          )
                        )
                      )
             )

}