library(shiny)
library(scales)
library(bslib)
library(DT)
library(shinyMatrix)

ui <- navbarPage(
  title = "MASLD Treatment Activity and Costs Modelling",
  id = "navbar",
  
  tabPanel("Introduction",
           fluidPage(
             h1("Introduction to the MASLD Treatment Activity and Costs Model"),
             p("Some explanatory text"),
             navset_tab(
               nav_panel("How to use the tool"),
               nav_panel("Explanation of Assumptions"),
               nav_panel("Modelling Documentation")
             )
           )
  ),
  
  tabPanel(title = "Population Assumptions",
           fluidPage(
             sidebarLayout(
               sidebarPanel(
                 h4("Set Adult Population:"),
                 numericInput("adult_pop",
                              "Set Adult Population:",
                              value = 10000,
                              min = 0,
                              step = 10000),
                 h4("Set the MASLD and MASH Prevalence:"),
                 sliderInput("masld_prev",
                             "Set MASLD Prevalence:",
                             value = 24,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("masld_prev_tol",
                             "Set MASLD Prevalence tolerance:",
                             value = 5,
                             min = 0,
                             max = 25,
                             step = 0.5,
                             post = "%"),
                 sliderInput("mash_prev",
                             "Set MASH Prevalence:",
                             value = 4.5,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("mash_prev_tol",
                             "Set MASH Prevalence tolerance:",
                             value = 1,
                             min = 0,
                             max = 10,
                             step = 0.25,
                             post = "%"),
                 br(),
                 h4("Set the Fibrosis Stage Assumptions"),
                 sliderInput("F0_prop",
                             "Set proportion at stage F0:",
                             value = 23,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("F1_prop",
                             "Set the proportion at stage F1:",
                             value = 36,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("F2_prop",
                             "Set the proportion at stage F2:",
                             value = 20,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("F3_prop",
                             "Set the proportion at stage F3:",
                             value = 13,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("F4_prop",
                             "Set the proportion at stage F4:",
                             value = 8,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 br(),
                 h4("Set the Prevalence rates of Obesity and Diabetes"),
                 sliderInput("ob_prev",
                             "Prevalence of obesity within MASLD population:",
                             value = 55,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("ob_prev_tol",
                             "Set the obesity prevalence tolerance:",
                             value = 10,
                             min = 0,
                             max = 20,
                             step = 1,
                             post = "%"),
                 sliderInput("t2d_prev",
                             "Prevalence of Type 2 Diabetes within MASLD population",
                             value = 30,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("t2d_prev_tol",
                             "Set the Type 2 Diabetes prevalence tolerance:",
                             value = 12,
                             min = 0,
                             max = 25,
                             step = 1,
                             post = "%"),
                 br(),
                 h4("Set the diagnosis rates for each Fibrosis Stage:"),
                 sliderInput("diag_F0",
                             "Set the diagnosis rate for F0:",
                             value = 2,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("diag_F1",
                             "Set the diagnosis rate for F1:",
                             value = 2,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("diag_F2",
                             "Set the diagnosis rate for F2:",
                             value = 16.5,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("diag_F3",
                             "Set the diagnosis rate for F3:",
                             value = 58.3,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 sliderInput("diag_F4",
                             "Set the diagnosis rate for F4:",
                             value = 100,
                             min = 0,
                             max = 100,
                             step = 1,
                             post = "%"),
                 br(),
                 h4("Download Assumptions"),
                 downloadButton("download_assumptions", "Download Assumptions")
               ),
               mainPanel(
                 h1("Population Assumptions"),
                 h3("Prevalence"),
                 p("The tabs below show the simulated MASLD populations to be used within the model as either a histogram or table:"),
                 textOutput("masld_prev"),
                 navset_tab(
                   nav_panel("Histogram", plotOutput("masld_pop_histogram")),
                   nav_panel("Table", DTOutput("masld_pop_DT"))
                 ),
                 h3("MASH Prevalence"),
                 p("The tabs below show the simulated MASH populations to be used within the model as either a histogram or table:"),
                 navset_tab(
                   nav_panel("Histogram", plotOutput("mash_pop_histogram")),
                   nav_panel("Table", DTOutput("mash_pop_DT"))
                 ),
                 h3("Fibrosis Stage Populations"),
                 p("The tabs below show the simulated MASH populations by Fibrosis stage that will be used within the model as either a histogram or table:"),
                 navset_tab(
                   nav_panel("Histogram", plotOutput("f_stage_pop_histogram")),
                   nav_panel("Table", DTOutput("f_stage_pop_DT"))
                 ),
                 h3("Co-morbidities"),
                 p("TODO"),
                 h3("Diagnosed Population Estimates"),
                 p("The tabs below show the estimated population at each Fibrosis stage that is diagnosed. This is shown as either a histogram or a table:"),
                 navset_tab(
                   nav_panel("Histogram", plotOutput("f_stage_diag_histogram")),
                   nav_panel("Table", DTOutput("f_stage_diag_DT"))
                 ),
                 
               )
             )
           )
  ),
  
  tabPanel(title = "Treatment Implementation",
           fluidPage(
             h1("Populations receiving treatments"),
             p("In this section please specify the proportion of each group who will receive each treatment type."),
             navset_tab(
               nav_panel("Semaglutide",
                         sidebarLayout(
                           sidebarPanel(
                                h3("Semaglutide"),
                                hr(),
                                sliderInput("treat_pop_F0_sem",
                                            "Select the proportion of F0 patients receiving treatment:",
                                            value = 0,
                                            min = 0,
                                            max = 100,
                                            post = "%"),
                                sliderInput("treat_pop_F1_sem",
                                            "Select the proportion of F1 patients receiving treatment:",
                                            value = 0,
                                            min = 0,
                                            max = 100,
                                            post = "%"),
                                sliderInput("treat_pop_F2_sem",
                                            "Select the proportion of F2 patients receiving treatment:",
                                            value = 40,
                                            min = 0,
                                            max = 100,
                                            post = "%"),
                                sliderInput("treat_pop_F3_sem",
                                            "Select the proportion of F3 patients receiving treatment:",
                                            value = 85,
                                            min = 0,
                                            max = 100,
                                            post = "%"),
                                sliderInput("treat_pop_F4_sem",
                                            "Select the proportion of F4 patients receiving treatment:",
                                            value = 0,
                                            min = 0,
                                            max = 100,
                                            post = "%")
                                ),
                           mainPanel(
                                h4("Table of treatment population"),
                                DTOutput("treat_pop_sem_DT")
                           )
                         )
               )
                         
             )
           )
  ),
  tabPanel(title = "Semaglutide Pathway Activity Assumptions",
           fluidPage(
             h1("Semaglutide Pathway Activity Assumptions"),
             p("In this section you can set the assumptions about the clinical activities that occur along the treatment pathway"),
             navset_tab(
               nav_panel("Pathway Assumptions",
                 fluidRow(
                   column(2,
                          h3("Pre-Treatment"),
                          hr(),
                          h4("Liver Biopsy"),
                          sliderInput("liver_biopsy_prop_sem",
                                      "Set Percentage undergoing biopsy:",
                                      value = 10,
                                      min = 0,
                                      max = 100,
                                      post = "%")
                   ),
                   column(2,
                          h3("Week 0"),
                          hr(),
                          h4("Baseline Testing"),
                          sliderInput("baseline_testing_elf_sem",
                                      "Set Percentage undergoing Baseline ELF:",
                                      value = 80,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          sliderInput("baseline_testing_biomarkers_sem",
                                      "Set Percentage undergoing Baseline biomarkers:",
                                      value = 20,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          selectInput("baseline_test_setting_sem",
                                      "Input setting for Baseline testing:",
                                      choice = c("Primary Care - GP",
                                                 "Primary Care - Nurse led",
                                                 "Secondary Care - Hepatologist"),
                                      selected = "Secondary Care - Hepatologist"),
                          matrixInput("baseline_testing_setting_matrix_sem",
                                      "Input setting for care setting of Baseline testing:",
                                      value = matrix(c(20, 30, 50), ncol = 1, byrow = TRUE,
                                                     dimnames = list(c("Primary Care - GP",
                                                                       "Primary Care - Nurse Led",
                                                                       "Secondary Care - Hepatologist"),
                                                                     c("Percentage (%)")
                                                                     )),
                                      class = "numeric",
                                      ),
                          hr(),
                          h4("Treatment Delivery"),
                          sliderInput("retention_sem_0_16",
                                      "Input retention on Semaglutide for 16 weeks:",
                                      value = 85,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          selectInput("semaglutide_0_16_delivery_setting",
                                      "Input the setting for delivery of Semaglutide for weeks 0-16:",
                                      choice = c("Primary Care - GP",
                                                 "Primary Care - Nurse led",
                                                 "Secondary Care - Hepatologist"),
                                      selected = "Secondary Care - Hepatologist")
                          
                   ),
                   column(2,
                          h3("Weeks 4-71: Monitoring"),
                          hr(),
                          h4("Monitoring Tests"),
                          numericInput("monitoring_tests_number_sem",
                                       "Select number of monitoring tests:",
                                       value = 9,
                                       min = 0,
                                       max = NA,
                                       step = 1),
                          sliderInput("monitoring_elf_prop_sem",
                                      "Select percentage of monitoring tests that are ELF:",
                                      value = 75,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          sliderInput("monitoring_bio_prop_sem",
                                      "Select percentage of monitoring tests that are biomarkers:",
                                      value = 25,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          hr(),
                          h4("Dosage Maintenence"),
                          sliderInput("dosage_retention_20_71_sem",
                                      "Select the retention rate of those at Dosage Maintenance:",
                                      value = 90,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          selectInput("semaglutide_20_71_delivery_setting",
                                      "Input the setting for delivery of Semaglutide for weeks 20-71:",
                                      choice = c("Primary Care - GP",
                                                 "Primary Care - Nurse led",
                                                 "Secondary Care - Hepatologist"),
                                      selected = "Secondary Care - Hepatologist")
                   ),
                   column(2,
                          h3("Week 72 - Continuation"),
                          hr(),
                          h4("Efficacy Assessment"),
                          sliderInput("efficacy_liver_biopsy_prop_sem",
                                      "Select the percentage of patients undergoing a liver biopsy:",
                                      value = 60,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          sliderInput("efficacy_elf_prop_sem",
                                      "Select the percentage of patients undergoing ELF testing:",
                                      value = 70,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          sliderInput("efficacy_biomarkers_prop_sem",
                                      "Select the percentage of patients undergoing biomarker testing:",
                                      value = 30,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          hr(),
                          h4("Continuation Decision"),
                          sliderInput("continuation_prop_sem",
                                      "Select the percentage of patients continuing with treatment:",
                                      value = 60,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          selectInput("continuation_delivery_setting_sem",
                                      "Input the setting for continuation decision appointment:",
                                      choice = c("Primary Care - GP",
                                                 "Primary Care - Nurse led",
                                                 "Secondary Care - Hepatologist"),
                                      selected = "Secondary Care - Hepatologist")
                   ),
                   column(2,
                          h3("Week 73-103 - Dosage Maintenance"),
                          hr(),
                          h4("Retention Rate"),
                          sliderInput("retention_73_103_sem",
                                      "Select the retention rate for patients receiving dosage maintenance:",
                                      value = 90,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          selectInput("semaglutide_73_103_delivery_setting",
                                      "Input the setting for delivery of Semaglutide for weeks 73-103:",
                                      choice = c("Primary Care - GP",
                                                 "Primary Care - Nurse led",
                                                 "Secondary Care - Hepatologist"),
                                      selected = "Secondary Care - Hepatologist"),
                          hr(),
                          h4("Monitoring Testing"),
                          numericInput("monitoring_tests_number_73_103_sem",
                                       "Select number of monitoring tests:",
                                       value = 3,
                                       min = 0,
                                       max = NA,
                                       step = 1),
                          sliderInput("monitoring_tests_73_103_elf_sem",
                                      "Select the percentage of patients undergoing ELF testing:",
                                      value = 75,
                                      min = 0,
                                      max = 100,
                                      post = "%")
                   ),
                   column(2,
                          h3("Week 104+ - Ongoing Treatment"),
                          hr(),
                          h4("Treatment Weeks to Model"),
                          numericInput("ongoing_period_sem",
                                       "Select the number of weeks to continue modelling treatment",
                                       value = 104,
                                       min = 52,
                                       max = 208,
                                       step = 1),
                          hr(),
                          h4("Retention by End-point"),
                          sliderInput("retention_end_sem",
                                      "Select the retention rate by the end-point of the model:",
                                      value = 75,
                                      min = 0,
                                      max = 100,
                                      post = "%"),
                          hr(),
                          h4("Ongoing Treatment Setting"),
                          selectInput("semaglutide_ongoing_delivery_setting",
                                      "Input the setting for delivery of Semaglutide until end-point:",
                                      choice = c("Primary Care - GP",
                                                 "Primary Care - Nurse led",
                                                 "Secondary Care - Hepatologist"),
                                      selected = "Secondary Care - Hepatologist")
                   )
                 )
               ),
               nav_panel("Pathway Map",
                         includeHTML("www/images/DRAFT MASLD Treatment Formatted v0.6 for AB.drawio.html")
             )
            )
           )
  ),
  tabPanel(title = "Survodutide Pathway Activity Assumptions",
           fluidPage(
             h1("Survodutide Pathway Activity Assumptions"),
             p(),
             navset_tab(
               nav_panel("Pathway Assumptions"
                         ),
               nav_panel("Pathway Map",
                         includeHTML("www/images/DRAFT MASLD Treatment Formatted v0.6 for AB.drawio.html")
               )
             )
           )
  ),
  tabPanel(title = "Resmetirom Pathway Activity Assumptions",
           fluidPage(
             h1("Resmetirom Pathway Activity Assumptions"),
             p(),
             navset_tab(
               nav_panel("Pathway Assumptions"
               ),
               nav_panel("Pathway Map",
                         includeHTML("www/images/DRAFT MASLD Treatment Formatted v0.6 for AB.drawio.html")
               )
             )
           )
  ),
  tabPanel(title = "Lanifibranor Pathway Activity Assumptions",
           fluidPage(
             h1("Lanifibranor Pathway Activity Assumptions"),
             p(),
             navset_tab(
               nav_panel("Pathway Assumptions"
               ),
               nav_panel("Pathway Map",
                         includeHTML("www/images/DRAFT MASLD Treatment Formatted v0.6 for AB.drawio.html")
               )
             )
           )
  ),
  tabPanel(title = "Financial Assumptions"),
  tabPanel(title = "Model Outputs - Activity and Costs",
           fluidPage(
           h1("Model Outputs"),
           p("Some explanatory notes"),
           h3("Patients Receiving Treatment"),
           navset_tab(
             nav_panel("Semaglutide"
             ),
             nav_panel("Survodutide"
             ),
             nav_panel("Resmetirom"
             ),
             nav_panel("Lanifibranor"
             ),
             nav_panel("All Treamtents"
             )
           ),
           h3("Pre-Treatment"),
           h4("Liver Biopsies"),
           p("Some text on Liver Biopsies"),
           navset_tab(
             nav_panel("Semaglutide",
                       navset_tab(
                         nav_panel("Summary"),
                         nav_panel("Data Table", DTOutput("pre_treat_biopsy_sem_DT"))
                       )
             ),
             nav_panel("Survodutide"
             ),
             nav_panel("Resmetirom"
             ),
             nav_panel("Lanifibranor"
             ),
             nav_panel("All Treamtents"
             )
           )
           )
  )
)