---
title: "MASLD Treatment Model Assumptions Guidance"
author: "<a href='https://github.com/ASW-Analyst/'>Andy Wilson</a><br><a href='https://transformationunit.nhs.uk/'>NHS Transformation Unit</a>"
date: "03/10/2025"
date-format: "DD MMMM YYYY"
format:
  html:
    toc: true
    toc-depth: 2
    toc-location: left
    self-contained: true
    css: ../../src/config/nhse_theme.css
    number-sections: true

---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  out.width = '100%'
)

library(here)

```

# Introduction

***

The purpose of this documentation is to provide guidance on all model input parameters. This guidance covers:

* A description of the purpose of the input
* The format the input takes and any restrictions (i.e. percentage)
* Interactions or dependencies with other inputs
* The calculations the input is utilised in

<br/>

# Population Assumptions

***

This section contains the guidance on the assumptions applied within **Population Assumptions** tab.

## Population
The first assumption to apply is the adult population for the geography being modelled.

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Pop_1**  | `adult_pop`    | This input sets the adult population for the area you are intending to model and can be taken from ONS population estimates for those aged 18+ years | Integer    | N/A   | This is used with calculations to model the number of patients with MASLD or MASH based on input prevalence rates |

<br/>

## Prevalence Rates
Prevalence rates for MASLD and MASH are required to determine the number of patients who have the conditions (whether diagnosed or undiagnosed).

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Pop_2.1.1**| `masld_prev`   | The prevalence of MASLD within the adult population. | Percentage | Limited to between 0 and 100% | Used in conjunction with **Pop_1** to determine the number of patients with MASLD |
| **Pop_2.1.2**| `masld_prev_tol` | The tolerance range to apply for sensitivities to the MASLD disease prevalence. For example, if the prevalence is set at 24% and a tolerance range of 5% this would set a lower tolerance of 19% prevalence and an upper of 29% prevalence. | Percentage | Used to calculate the percentage of patients with MASLD for the lower and upper estimates. Also used for simulations 4:100 as limits to sample from. | Used in conjunction with **Pop_1** to determine the number of patients with MASLD for sensitivities. | 
| **Pop_2.2.1** | `mash_prev` | The prevalence of MASH within the adult population. | Percentage | Limited to between 0 and 100% | Used in conjunction with **Pop_1** to determine the number of patients with MASH | 
| **Pop_2.2.2**| `mash_prev_tol` | The tolerance range to apply for sensitivities to the MASH disease prevalence. For example, if the prevalence is set at 4% and a tolerance range of 2% this would set a lower tolerance of 2% prevalence and an upper of 6% prevalence. | Percentage | Used to calculate the percentage of patients with MASH for the lower and upper estimates. Also used for simulations 4:100 as limits to sample from. | Used in conjunction with **Pop_1** to determine the number of patients with MASH for sensitivities. | 

<br/>

## Fibrosis Stage Assumptions
Next it is necessary to determine the breakdown of patients with MASH by fibrosis stage. The **Treatment Intentions** assumptions applied later apply assumptions to the population at each fibrosis stage.

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Pop_3.1.1** | `F0_prop`   | The percentage of MASH patients who are at fibrosis stage 0 | Percentage | Alongside other fibrosis stages assumptions **Pop_3.1.2**, **Pop_3.1.3**, **Pop_3.1.4**, **Pop_3.1.5** these need to sum to 100%. | Applied to **Pop_2.2.1** to determine the number of patients at stage F0. |
| **Pop_3.1.2** | `F1_prop`   | The percentage of MASH patients who are at fibrosis stage 1 | Percentage | Alongside other fibrosis stages assumptions **Pop_3.1.1**, **Pop_3.1.3**, **Pop_3.1.4**, **Pop_3.1.5** these need to sum to 100%. | Applied to **Pop_2.2.1** to determine the number of patients at stage F1. |
| **Pop_3.1.3** | `F2_prop`   | The percentage of MASH patients who are at fibrosis stage 2 | Percentage | Alongside other fibrosis stages assumptions **Pop_3.1.1**, **Pop_3.1.2**, **Pop_3.1.4**, **Pop_3.1.5** these need to sum to 100%. | Applied to **Pop_2.2.1** to determine the number of patients at stage F2. |
| **Pop_3.1.4** | `F3_prop`   | The percentage of MASH patients who are at fibrosis stage 3 | Percentage | Alongside other fibrosis stages assumptions **Pop_3.1.1**, **Pop_3.1.2**, **Pop_3.1.3**, **Pop_3.1.5** these need to sum to 100%. | Applied to **Pop_2.2.1** to determine the number of patients at stage F3. |
| **Pop_3.1.5** | `F4_prop`   | The percentage of MASH patients who are at fibrosis stage 4 | Percentage | Alongside other fibrosis stages assumptions **Pop_3.1.1**, **Pop_3.1.2**, **Pop_3.1.3**, **Pop_3.1.4** these need to sum to 100%. | Applied to **Pop_2.2.1** to determine the number of patients at stage F4. |

<br/>

## Comorbidity Prevalence
A key part of the determining the population who are eligible for treatment involves understanding those who may be receiving treatment via another pathway such as obesity or diabetes. Therefore, modelling the population of patients with these comorbidities is a critical first step.

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Pop_4.1.1** | `ob_prev`   | The prevalence of obesity in the population of patients with MASLD/MASH | Percentage | Limited to between 0 and 100% | Applied to population of patients at each fibrosis stage to determine number of those who are obese. | 
| **Pop_4.1.2** | `ob_prev_tol` | The tolerance range to apply for sensitivities to the obesity prevalence. | Percentage | Limited to between 0 and 20% | Applied to the population of patients at each fibrosis stage to calculate the lower and upper sensitivities and for setting limits for generating the other 97 simulations. |
| **Pop_4.2.1** | `t2d_prev`   | The prevalence of type 2 diabetes in the population of patients with MASLD/MASH | Percentage | Limited to between 0 and 100% | Applied to population of patients at each fibrosis stage to determine number of those who have type 2 diabetes. | 
| **Pop_4.2.2** | `t2d_prev_tol` | The tolerance range to apply for sensitivities to the type 2 diabetes prevalence. | Percentage | Limited to between 0 and 25% | Applied to the population of patients at each fibrosis stage to calculate the lower and upper sensitivities and for setting limits for generating the other 97 simulations. |

<br/>

## Diagnosis Rates
These assumptions are applied to determine the **diagnosed (i.e. known) population ** of patients by fibrosis stage.

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Pop_5.1** | `diag_F0` | The percentage of the F0 population who are diagnosed | Percentage | Limited to between 0 and 100% | Applied to the population of patients at F0. |
| **Pop_5.2** | `diag_F1` | The percentage of the F1 population who are diagnosed | Percentage | Limited to between 0 and 100% | Applied to the population of patients at F1. |
| **Pop_5.3** | `diag_F2` | The percentage of the F2 population who are diagnosed | Percentage | Limited to between 0 and 100% | Applied to the population of patients at F2. |
| **Pop_5.4** | `diag_F3` | The percentage of the F3 population who are diagnosed | Percentage | Limited to between 0 and 100% | Applied to the population of patients at F3. |
| **Pop_5.5** | `diag_F4` | The percentage of the F4 population who are diagnosed | Percentage | Limited to between 0 and 100% | Applied to the population of patients at F4. |

<br/>

## Already Receiving Treatment
To remove patients who are already receiving treatment these assumptions are applied to those patients with either comorbidity.

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Pop_6.1** | `treat_other_F0` | The percentage of the diagnosed F0 population with a comorbidity that are already receiving treatment | Percentage | Limited to between 0 and 100% | Applied to the population of diagnosed F0 patients who have either comorbidity. This is determined as the sum of the two comorbidities minus 12.4% to account for the intersection of both. |
| **Pop_6.2** | `treat_other_F1` | The percentage of the diagnosed F1 population with a comorbidity that are already receiving treatment | Percentage | Limited to between 0 and 100% | Applied to the population of diagnosed F1 patients who have either comorbidity. This is determined as the sum of the two comorbidities minus 12.4% to account for the intersection of both. |
| **Pop_6.3** | `treat_other_F2` | The percentage of the diagnosed F2 population with a comorbidity that are already receiving treatment | Percentage | Limited to between 0 and 100% | Applied to the population of diagnosed F2 patients who have either comorbidity. This is determined as the sum of the two comorbidities minus 12.4% to account for the intersection of both. |
| **Pop_6.4** | `treat_other_F3` | The percentage of the diagnosed F3 population with a comorbidity that are already receiving treatment | Percentage | Limited to between 0 and 100% | Applied to the population of diagnosed F3 patients who have either comorbidity. This is determined as the sum of the two comorbidities minus 12.4% to account for the intersection of both. |
| **Pop_6.5** | `treat_other_F4` | The percentage of the diagnosed F4 population with a comorbidity that are already receiving treatment | Percentage | Limited to between 0 and 100% | Applied to the population of diagnosed F4 patients who have either comorbidity. This is determined as the sum of the two comorbidities minus 12.4% to account for the intersection of both. |

<br/>

# Treatment Implementation
These assumptions are applied to the diagnosed populations who aren't receiving treatment to determine the number of patients that are intended to start treatment within the model. They are split into four sections, one for each treatment pathway.

## Semaglutide

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **TI_Sem_1.1** | `treat_pop_F0_sem` | The percentage of the F0 population to start treatment with Semaglutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Surv_1.1**, **TI_Res_1.1** and **TI_Lan_1.1** to ensure that no more than 100% of F0 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F0 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Sem_1.2** | `treat_pop_F1_sem` | The percentage of the F1 population to start treatment with Semaglutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Surv_1.2**, **TI_Res_1.2** and **TI_Lan_1.2** to ensure that no more than 100% of F1 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F1 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Sem_1.3** | `treat_pop_F2_sem` | The percentage of the F2 population to start treatment with Semaglutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Surv_1.3**, **TI_Res_1.3** and **TI_Lan_1.3** to ensure that no more than 100% of F2 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F2 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Sem_1.4** | `treat_pop_F3_sem` | The percentage of the F3 population to start treatment with Semaglutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Surv_1.4**, **TI_Res_1.4** and **TI_Lan_1.4** to ensure that no more than 100% of F3 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F3 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Sem_1.5** | `treat_pop_F4_sem` | The percentage of the F4 population to start treatment with Semaglutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Surv_1.5**, **TI_Res_1.5** and **TI_Lan_1.5** to ensure that no more than 100% of F4 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F4 patients not receiving treatment to calculate the number starting treatment. |

<br/>

## Survodutide

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **TI_Surv_1.1** | `treat_pop_F0_surv` | The percentage of the F0 population to start treatment with Survodutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.1**, **TI_Res_1.1** and **TI_Lan_1.1** to ensure that no more than 100% of F0 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F0 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Surv_1.2** | `treat_pop_F1_surv` | The percentage of the F1 population to start treatment with Survodutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.2**, **TI_Res_1.2** and **TI_Lan_1.2** to ensure that no more than 100% of F1 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F1 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Surv_1.3** | `treat_pop_F2_surv` | The percentage of the F2 population to start treatment with Survodutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.3**, **TI_Res_1.3** and **TI_Lan_1.3** to ensure that no more than 100% of F2 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F2 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Surv_1.4** | `treat_pop_F3_surv` | The percentage of the F3 population to start treatment with Survodutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.4**, **TI_Res_1.4** and **TI_Lan_1.4** to ensure that no more than 100% of F3 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F3 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Surv_1.5** | `treat_pop_F4_surv` | The percentage of the F4 population to start treatment with Survodutide | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.5**, **TI_Res_1.5** and **TI_Lan_1.5** to ensure that no more than 100% of F4 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F4 patients not receiving treatment to calculate the number starting treatment. |

<br/>

## Resmetirom

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **TI_Res_1.1** | `treat_pop_F0_res` | The percentage of the F0 population to start treatment with Resmetirom | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.1**, **TI_Surv_1.1** and **TI_Lan_1.1** to ensure that no more than 100% of F0 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F0 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Res_1.2** | `treat_pop_F1_res` | The percentage of the F1 population to start treatment with Resmetirom | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.2**, **TI_Surv_1.2** and **TI_Lan_1.2** to ensure that no more than 100% of F1 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F1 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Res_1.3** | `treat_pop_F2_res` | The percentage of the F2 population to start treatment with Resmetirom | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.3**, **TI_Surv_1.3** and **TI_Lan_1.3** to ensure that no more than 100% of F2 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F2 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Res_1.4** | `treat_pop_F3_res` | The percentage of the F3 population to start treatment with Resmetirom | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.4**, **TI_Surv_1.4** and **TI_Lan_1.4** to ensure that no more than 100% of F3 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F3 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Res_1.5** | `treat_pop_F4_res` | The percentage of the F4 population to start treatment with Resmetirom | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.5**, **TI_Surv_1.5** and **TI_Lan_1.5** to ensure that no more than 100% of F4 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F4 patients not receiving treatment to calculate the number starting treatment. |

<br/>

## Lanifibranor

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **TI_Lan_1.1** | `treat_pop_F0_lan` | The percentage of the F0 population to start treatment with Lanifibranor | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.1**, **TI_Surv_1.1** and **TI_Res_1.1** to ensure that no more than 100% of F0 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F0 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Lan_1.2** | `treat_pop_F1_lan` | The percentage of the F1 population to start treatment with Lanifibranor | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.2**, **TI_Surv_1.2** and **TI_Res_1.2** to ensure that no more than 100% of F1 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F1 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Lan_1.3** | `treat_pop_F2_lan` | The percentage of the F2 population to start treatment with Lanifibranor | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.3**, **TI_Surv_1.3** and **TI_Res_1.3** to ensure that no more than 100% of F2 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F2 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Lan_1.4** | `treat_pop_F3_lan` | The percentage of the F3 population to start treatment with Lanifibranor | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.4**, **TI_Surv_1.4** and **TI_Res_1.4** to ensure that no more than 100% of F3 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F3 patients not receiving treatment to calculate the number starting treatment. |
| **TI_Lan_1.5** | `treat_pop_F4_lan` | The percentage of the F4 population to start treatment with Lanifibranor | Percentage | Limited to between 0 and 100. Needs to be considered against **TI_Sem_1.5**, **TI_Surv_1.5** and **TI_Res_1.5** to ensure that no more than 100% of F4 patients start treatment. Unless you are modelling patients receiving multiple treatments. | Applied to the population of diagnosed F4 patients not receiving treatment to calculate the number starting treatment. |

<br/>

# Semaglutide Pathway Activity Assumptions

***

The following assumptions relate to activities for patients on the Semaglutide treatment pathway.

## Pre-Treament

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Sem_1.1.1** | `mm_assess_prop_sem` | Percentage of patients starting treatment who will undergo an initial eligibility assessment. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients starting treatment. |
| **Sem_1.1.2** | `mm_assess_setting_sem` | Set the percentage of initial eligibility assessments taking place across the six locations. Also set the number of minutes for each assessment | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the total population starting treatment with Semaglutide. The number of minutes are then applied to this activity. |
| **Sem_1.2** | `pre_liver_biopsy_prop_sem` | The percentage of population starting treatment with Semaglutide undergoing a liver biopsy at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine liver biopsy activities. |
| **Sem_1.3** | `pre_elf_prop_sem` | The percentage of population starting treatment with Semaglutide undergoing an ELF test at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine ELF activities. |
| **Sem_1.4** | `pre_biomarkers_prop_sem` | The percentage of population starting treatment with Semaglutide undergoing biomarker testing at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine biomarker activities. |
| **Sem_1.5** | `pre_fibro_prop_sem` | The percentage of population starting treatment with Semaglutide undergoing FibroScan at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine FibroScan activities. |


<br/>

## Week 0: Treatment Delivery
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Sem_2.1** | `retention_sem_0_16` | Percentage of patients who started treatment who remain on treatment at 16 weeks. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients starting treatment. |
| **Sem_2.2.1** | `treatment_setting_0_16_matrix_sem` | Set the percentage of initial treatment delivery appointments taking place across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the total population starting treatment with Semaglutide. The number of minutes are then applied to this activity. |
| **Sem_2.2.2** | `appts_0_16_sem` | Set the number of appointments taking place over weeks 0-16.| Numeric value | N/A | N/A |


## Weeks 4-71: Monitoring and Dosage Maintenance
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Sem_3.1.1** | `monitoring_tests_number_sem` | Set the number of monitoring tests taking place over weeks 4-71.| Numeric value | N/A | N/A |
| **Sem_3.1.2** | `monitoring_elf_prop_sem` | The percentage of monitoring tests taking place over weeks 4-71 that are ELF tests. | Percentage | Limited from 0 to 100% | N/A |
| **Sem_3.1.3** | `monitoring_bio_prop_sem` | The percentage of monitoring tests taking place over weeks 4-71 that are biomarkers. | Percentage | Limited from 0 to 100% | N/A |
| **Sem_3.2** | `dosage_retention_20_71_sem` | Percentage of patients who were receiving treatment at week 16 who remain on treatment at week 71. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients on treatment at week 16. |
| **Sem_3.3** | `semaglutide_20_71_delivery_setting` | Set the percentage of treatment delivery appointments taking place over weeks 20-71 across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population on treatment with Semaglutide at week 16. The number of minutes are then applied to this activity. |
| **Sem_3.4** | `appts_20_71_sem` | Set the number of appointments taking place over weeks 20-71.| Numeric value | N/A | N/A |


## Week 72: Continuation Decision
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Sem_4.1** | `efficacy_liver_biopsy_prop_sem` | The percentage of population remaining on treatment at week 72 undergoing a liver biopsy to assess efficacy. | Percentage | Limited from 0 to 100% | Applied to the population remaining on treatment at week 72 to determine liver biopsy activities. |
| **Sem_4.2** | `efficacy_elf_prop_sem` | The percentage of population remaining on treatment at week 72 undergoing ELF testing to assess efficacy. | Percentage | Limited from 0 to 100% | Applied to the population remaining on treatment at week 72 to determine ELF activities. |
| **Sem_4.3** | `efficacy_fibro_prop_sem` | The percentage of population remaining on treatment at week 72 undergoing a FibroScan to assess efficacy. | Percentage | Limited from 0 to 100% | Applied to the population remaining on treatment at week 72 to determine FibroScan activities. |
| **Sem_4.4** | `efficacy_biomarkers_prop_sem` | The percentage of population remaining on treatment at week 72 undergoing biomarker testing to assess efficacy.| Percentage | Limited from 0 to 100% | Applied to the population remaining on treatment at week 72 to determine biomarker activities. |
| **Sem_4.5.1** | `continuation_prop_sem` | The percentage of population remaining on treatment at week 72 continuing with treatment. | Percentage | Limited to 0 and 100% | Applied to the population remaining on treatment at week 72.|
| **Sem_4.5.2** | `continuation_delivery_setting_sem` | Set the percentage of continuation decision appointments taking place across the six locations. Also set the number of minutes for each assessment | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population remaining on treatment at week 72. The number of minutes are then applied to this activity. |

## Week 73-103: Dosage Maintenance
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Sem_5.1** | `retention_73_103_sem` | Percentage of patients on treatment at week 73 who remain on treatment at week 103. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients receiving treatment at week 73. |
| **Sem_5.2.1** | `semaglutide_73_103_delivery_setting` | Set the percentage of treatment delivery appointments over weeks 73-103 taking place across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population receiving treatment with Semaglutide at week 73. The number of minutes are then applied to this activity. |
| **Sem_5.2.2** | `appts_73_103_sem` | Set the number of appointments taking place over weeks 73-103.| Numeric value | N/A | N/A |
| **Sem_5.3.1** | `monitoring_tests_number_73_103_sem` | Set the number of monitoring tests taking place over weeks 73-103.| Numeric value | N/A | N/A |
| **Sem_5.3.2** | `monitoring_tests_73_103_elf_sem` | The percentage of monitoring tests taking place over weeks 73-103 that are ELF tests. | Percentage | Limited from 0 to 100% | N/A |
| **Sem_5.3.3** | `monitoring_tests_73_103_biomarkers_sem` | The percentage of monitoring tests taking place over weeks 73-103 that are biomarkers. | Percentage | Limited from 0 to 100% | N/A |


## Week 104+: Ongoing Treatment
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Sem_6.1** | `ongoing_period_sem` | Set the number of weeks treatment is continued.| Numeric value | N/A | N/A |
| **Sem_6.2** | `retention_end_sem` | Percentage of patients who were receiving treatment at week 103 who remain on treatment at the end of the model. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients on treatment at week 103. |
| **Sem_6.3.1** | `semaglutide_ongoing_delivery_setting` | Set the percentage of treatment delivery appointments from week 104 to end point taking place across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population receiving treatment with Semaglutide at week 103. The number of minutes are then applied to this activity. |
| **Sem_6.3.2** | `appts_ongoing_sem` | Set the number of appointments taking place from week 104 to end point.| Numeric value | N/A | N/A |
| **Sem_6.4** | `ongoing_annual_prop_elf_sem` | The percentage of annual assessments for Semaglutide including an ELF test. | Percentage | Limited from 0 to 100% | N/A |
| **Sem_6.5** | `ongoing_annual_prop_biomarkers_sem` | The percentage of annual assessments for Semaglutide including biomarkers. | Percentage | Limited from 0 to 100% | N/A |
| **Sem_6.6** | `ongoing_annual_prop_fibro_sem` | The percentage of annual assessments for Semaglutide including FibroScan. | Percentage | Limited from 0 to 100% | N/A |



# Survodutide Pathway Activity Assumptions

***

The following assumptions relate to activities for patients on the Survodutide treatment pathway.

## Pre-Treament

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Surv_1.1.1** | `mm_assess_prop_surv` | Percentage of patients starting treatment who will undergo an initial eligibility assessment. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients starting treatment. |
| **Surv_1.1.2** | `mm_assess_setting_surv` | Set the percentage of initial eligibility assessments taking place across the six locations. Also set the number of minutes for each assessment | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the total population starting treatment with Survodutide. The number of minutes are then applied to this activity. |
| **Surv_1.2** | `pre_liver_biopsy_prop_surv` | The percentage of population starting treatment with Survodutide undergoing a liver biopsy at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine liver biopsy activities. |
| **Surv_1.3** | `pre_elf_prop_surv` | The percentage of population starting treatment with Survodutide undergoing an ELF test at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine ELF activities. |
| **Surv_1.4** | `pre_biomarkers_prop_surv` | The percentage of population starting treatment with Survodutide undergoing biomarker testing at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine biomarker activities. |
| **Surv_1.5** | `pre_fibro_prop_surv` | The percentage of population starting treatment with Survodutide undergoing FibroScan at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine FibroScan activities. |


## Week 0: Treatment Delivery 

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Surv_2.1** | `retention_surv_0_24` | Percentage of patients who started treatment who remain on treatment at 24 weeks. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients starting treatment. |
| **Surv_2.2.1** | `treatment_setting_0_24_matrix_surv` | Set the percentage of initial treatment delivery appointments taking place across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the total population starting treatment with Survodutide. The number of minutes are then applied to this activity. |
| **Surv_2.2.2** | `appts_0_24_surv` | Set the number of appointments taking place over weeks 0-24.| Numeric value | N/A | N/A |


## Week 0-71: Monitoring and Dosage Maintenance

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Surv_3.1.1** | `monitor_tests_0_71_num_surv` | Set the number of monitoring tests taking place over weeks 0-71.| Numeric value | N/A | N/A |
| **Surv_3.1.2** | `monitor_tests_0_71_elf_prop_surv` | The percentage of monitoring tests taking place over weeks 0-71 that are ELF tests. | Percentage | Limited from 0 to 100% | N/A |
| **Surv_3.1.3** | `monitor_tests_0_71_bio_prop_surv` | The percentage of monitoring tests taking place over weeks 0-71 that are biomarkers. | Percentage | Limited from 0 to 100% | N/A |
| **Surv_3.2** | `retention_25_71_surv` | Percentage of patients who were receiving treatment at week 25 who remain on treatment at week 71. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients on treatment at week 25. |
| **Surv_3.3** | `treatment_setting_25_71_matrix_surv` | Set the percentage of treatment delivery appointments taking place over weeks 25-71 across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population on treatment with Survodutide at week 25. The number of minutes are then applied to this activity. |

## Week 72: Continuation Decision 

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Surv_4.1** | `efficacy_liver_biopsy_surv` | The percentage of population remaining on treatment at week 72 undergoing a liver biopsy to assess efficacy. | Percentage | Limited from 0 to 100% | Applied to the population remaining on treatment at week 72 to determine liver biopsy activities. |
| **Surv_4.2** | `efficacy_elf_prop_surv` | The percentage of population remaining on treatment at week 72 undergoing ELF testing to assess efficacy. | Percentage | Limited from 0 to 100% | Applied to the population remaining on treatment at week 72 to determine ELF activities. |
| **Surv_4.3** | `efficacy_fibro_prop_surv` | The percentage of population remaining on treatment at week 72 undergoing a FibroScan to assess efficacy. | Percentage | Limited from 0 to 100% | Applied to the population remaining on treatment at week 72 to determine FibroScan activities. |
| **Surv_4.4** | `efficacy_biomarkers_prop_surv` | The percentage of population remaining on treatment at week 72 undergoing biomarker testing to assess efficacy.| Percentage | Limited from 0 to 100% | Applied to the population remaining on treatment at week 72 to determine biomarker activities. |
| **Surv_4.5.1** | `continuation_prop_surv` | The percentage of population remaining on treatment at week 72 continuing with treatment. | Percentage | Limited to 0 and 100% | Applied to the population remaining on treatment at week 72.|
| **Surv_4.5.2** | `continuation_delivery_setting_surv` | Set the percentage of continuation decision appointments taking place across the six locations. Also set the number of minutes for each assessment | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population remaining on treatment at week 72. The number of minutes are then applied to this activity. |


## Week 73-103: Dosage Mainenance
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Surv_5.1** | `retention_73_103_surv` | Percentage of patients on treatment at week 73 who remain on treatment at week 103. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients receiving treatment at week 73. |
| **Surv_5.2.1** | `treatment_setting_73_103_matrix_surv` | Set the percentage of treatment delivery appointments over weeks 73-103 taking place across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population receiving treatment with Survodutide at week 73. The number of minutes are then applied to this activity. |
| **Surv_5.2.2** | `appts_73_103_surv` | Set the number of appointments taking place over weeks 73-103.| Numeric value | N/A | N/A |
| **Surv_5.3.1** | `monitoring_tests_number_73_103_surv` | Set the number of monitoring tests taking place over weeks 73-103.| Numeric value | N/A | N/A |
| **Surv_5.3.2** | `monitoring_tests_73_103_elf_surv` | The percentage of monitoring tests taking place over weeks 73-103 that are ELF tests. | Percentage | Limited from 0 to 100% | N/A |
| **Surv_5.3.3** | `monitoring_tests_73_103_biomarkers_surv` | The percentage of monitoring tests taking place over weeks 73-103 that are biomarkers. | Percentage | Limited from 0 to 100% | N/A |



## Week 104+: Ongoing Treatment 
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Surv_6.1** | `ongoing_period_surv` | Set the number of weeks treatment is continued.| Numeric value | N/A | N/A |
| **Surv_6.2** | `retention_end_surv` | Percentage of patients who were receiving treatment at week 103 who remain on treatment at the end of the model. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients on treatment at week 103. |
| **Surv_6.3.1** | `survodutide_ongoing_delivery_setting` | Set the percentage of treatment delivery appointments from week 104 to end point taking place across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population receiving treatment with Survodutide at week 103. The number of minutes are then applied to this activity. |
| **Surv_6.3.2** | `appts_ongoing_surv` | Set the number of appointments taking place from week 104 to end point.| Numeric value | N/A | N/A |
| **Surv_6.4** | `ongoing_annual_prop_elf_surv` | The percentage of annual assessments for Survodutide including an ELF test. | Percentage | Limited from 0 to 100% | N/A |
| **Surv_6.5** | `ongoing_annual_prop_biomarkers_surv` | The percentage of annual assessments for Survodutide including biomarkers. | Percentage | Limited from 0 to 100% | N/A |
| **Surv_6.6** | `ongoing_annual_prop_fibro_surv` | The percentage of annual assessments for Survodutide including FibroScan. | Percentage | Limited from 0 to 100% | N/A |



# Resmetirom Pathway Activity Assumptions

***

The following assumptions relate to activities for patients on the Resmetirom treatment pathway.

## Pre-Treament

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Res_1.1.1** | `mm_assess_prop_res` | Percentage of patients starting treatment who will undergo an initial eligibility assessment. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients starting treatment. |
| **Res_1.1.2** | `mm_assess_setting_res` | Set the percentage of initial eligibility assessments taking place across the six locations. Also set the number of minutes for each assessment | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the total population starting treatment with Resmetirom. The number of minutes are then applied to this activity. |
| **Res_1.2** | `pre_liver_biopsy_prop_res` | The percentage of population starting treatment with Resmetirom, undergoing a liver biopsy at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine liver biopsy activities. |
| **Res_1.3** | `pre_elf_prop_res` | The percentage of population starting treatment with Resmetirom undergoing an ELF test at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine ELF activities. |
| **Res_1.4** | `pre_biomarkers_prop_res` | The percentage of population starting treatment with Resmetirom undergoing biomarker testing at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine biomarker activities. |
| **Res_1.5** | `pre_fibro_prop_res` | The percentage of population starting treatment with Resmetirom undergoing FibroScan at baseline. | Percentage | Limited from 0 to 100% | Applied to the population starting treatment to determine FibroScan activities. |

## Weeks 0-52: Initial Treatment 

| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Res_2.1** | `dosage_0_52_res` | Percentage of patients starting treatment who are under 100kg. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patient starting treatment. |
| **Res_2.2** | `retention_res_0_52` | Percentage of patients who started treatment who remain on treatment at 52 weeks. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients starting treatment. |
| **Res_2.3.1** | `treatment_setting_0_52_matrix_res` | Set the percentage of initial treatment delivery appointments taking place across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the total population starting treatment with Resmetirom. The number of minutes are then applied to this activity. |
| **Res_2.3.2** | `appts_0_52_res` | Set the number of appointments taking place over weeks 0-52.| Numeric value | N/A | N/A |
| **Res_2.4.1** | `monitor_tests_0_52_res` | Set the number of monitoring tests taking place over weeks 0-52.| Numeric value | N/A | N/A |
| **Res_2.4.2** | `monitor_tests_0_52_elf_res` | The percentage of monitoring tests taking place over weeks 0-52 that are ELF tests. | Percentage | Limited from 0 to 100% | N/A |
| **Res_2.4.3** | `monitor_tests_0_52_biomarkers_res` | The percentage of monitoring tests taking place over weeks 0-52 that are biomarkers. | Percentage | Limited from 0 to 100% | N/A |
| **Res_2.4.4** | `monitor_tests_0_52_fibro_res` | The percentage of monitoring tests taking place over weeks 0-52 that are FibroScans. | Percentage | Limited from 0 to 100% | N/A |


## Weeks 52-71: Efficacy and Continuation
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Res_3.1** | `efficacy_52_liver_biopsy_res` | The percentage of population receiving treatment with Resmetirom at week 52 undergoing a liver biopsy to assess treatment efficacy. | Percentage | Limited from 0 to 100% | Applied to the population receiving treatment at week 52 to determine liver biopsy activities. |
| **Res_3.2** | `efficacy_52_elf_prop_res` | The percentage of population receiving treatment with Resmetirom at week 52 undergoing an ELF test to assess treatment efficacy. | Percentage | Limited from 0 to 100% | Applied to the population receiving treatment at week 52 to determine ELF activities. |
| **Res_3.3** | `efficacy_52_fibro_prop_res` |The percentage of population receiving treatment with Resmetirom at week 52 undergoing FibroScan to assess treatment efficacy. | Percentage | Limited from 0 to 100% | Applied to the population receiving treatment at week 52 to determine FibroScan activities. | 
| **Res_3.4** | `efficacy_52_biomarkers_prop_res` | The percentage of population receiving treatment with Resmetirom at week 52 undergoing biomarker testing to assess treatment efficacy. | Percentage | Limited from 0 to 100% | Applied to the population receiving treatment at week 52 to determine biomarker activities. |
| **Res_3.5.1** | `continuation_52_prop_res` | The percentage of the population continuing on treatment after week 52. | Percentage | Limited to 0 and 100% | Applied to the population remaining on treatment at week 52.|
| **Res_3.5.2** | `continuation_52_delivery_setting_res` | Set the percentage of continuation decision appointments taking place across the six locations. Also set the number of minutes for each assessment | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population remaining on treatment at week 52. The number of minutes are then applied to this activity. |
| **Res_3.6** | `retention_res_52_71` | Percentage of patients who continued treatment at week 52 who remain on treatment at week 71. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients who continued treatment at week 52. |
| **Res_3.7.1** | `treatment_setting_52_71_matrix_res` | Set the percentage of treatment delivery appointments taking place across the six locations over weeks 52-71. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the number of patients who continued treatment at week 52. The number of minutes are then applied to this activity. |
| **Res_3.7.2** | `appts_52_71_res` | Set the number of appointments taking place over weeks 52-71.| Numeric value | N/A | N/A |

## Week 72: Continuation Decision
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Res_4.1** | `efficacy_liver_biopsy_res` | The percentage of the population receiving treatment with Resmetirom at week 72 undergoing a liver biopsy to assess treatment efficacy. | Percentage | Limited from 0 to 100% | Applied to the population receiving treatment at week 72 to determine liver biopsy activities. |
| **Res_4.2** | `efficacy_elf_prop_res` | The percentage of population receiving treatment with Resmetirom at week 72 undergoing an ELF test to assess treatment efficacy. | Percentage | Limited from 0 to 100% | Applied to the population receiving treatment at week 72 to determine ELF activities. |
| **Res_4.3** | `efficacy_fibro_prop_res` | The percentage of population receiving treatment with Resmetirom at week 72 undergoing FibroScan to assess treatment efficacy. | Percentage | Limited from 0 to 100% | Applied to the population receiving treatment at week 72 to determine FibroScan activities. |
| **Res_4.4** | `efficacy_biomarkers_prop_res` | TThe percentage of population receiving treatment with Resmetirom at week 72 undergoing biomarker testing to assess treatment efficacy. | Percentage | Limited from 0 to 100% | Applied to the population receiving treatment at week 72 to determine biomarker activities. |
| **Res_4.5.1** | `continuation_prop_res` | The percentage of the population continuing on treatment after week 72. | Percentage | Limited to 0 and 100% | Applied to the population remaining on treatment at week 72.|
| **Res_4.5.2** | `continuation_delivery_setting_res` | Set the percentage of continuation decision appointments taking place across the six locations. Also set the number of minutes for each assessment | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population remaining on treatment at week 72. The number of minutes are then applied to this activity. |

## Week 73-103: Dosage Maintenance 
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Res_5.1** | `retention_73_103_res` | Percentage of patients on treatment at week 73 who remain on treatment at week 103. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients receiving treatment at week 73. |
| **Res_5.2.1** | `treatment_setting_73_103_matrix_res` | Set the percentage of treatment delivery appointments over weeks 73-103 taking place across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population receiving treatment with Resmetirom at week 73. The number of minutes are then applied to this activity. |
| **Res_5.2.2** | `appts_73_103_res` | Set the number of appointments taking place over weeks 73-103.| Numeric value | N/A | N/A |
| **Res_5.3.1** | `monitoring_tests_number_73_103_res` | Set the number of monitoring tests taking place over weeks 73-103.| Numeric value | N/A | N/A |
| **Res_5.3.2** | `monitoring_tests_73_103_elf_res` | The percentage of monitoring tests taking place over weeks 73-103 that are ELF tests. | Percentage | Limited from 0 to 100% | N/A |
| **Res_5.3.3** | `monitoring_tests_73_103_biomarkers_res` | The percentage of monitoring tests taking place over weeks 73-103 that are biomarkers. | Percentage | Limited from 0 to 100% | N/A |

## Week 104+: Ongoing Treatment 
| Input ID   | ID in Codebase | Description                     | Format    | Interactions or Dependencies | Calculations    |
|------------|----------------|---------------------------------|-----------|------------------------------|----------------------|
| **Res_6.1** | `ongoing_period_res` | Set the number of weeks treatment is continued.| Numeric value | N/A | N/A |
| **Res_6.2** | `retention_end_res` | Percentage of patients who were receiving treatment at week 103 who remain on treatment at the end of the model. | Percentage | Limited to 0 and 100% | This percentage is applied to the number of patients on treatment at week 103. |
| **Res_6.3.1** | `resmetirom_ongoing_delivery_setting` | Set the percentage of treatment delivery appointments from week 104 to end point taking place across the six locations. Also set the number of minutes for each treatment appointment. | Percentage for activity and numeric value for number of minutes | The sum of the percentages across each of the six settings should sum to 100% | The percentages are applied to the population receiving treatment with Resmetirom at week 103. The number of minutes are then applied to this activity. |
| **Res_6.3.2** | `appts_ongoing_res` | Set the number of appointments taking place from week 104 to end point.| Numeric value | N/A | N/A |
| **Res_6.4** | `ongoing_annual_prop_elf_res` | The percentage of annual assessments for Resmetirom including an ELF test. | Percentage | Limited from 0 to 100% | N/A |
| **Res_6.5** | `ongoing_annual_prop_biomarkers_res` | The percentage of annual assessments for Resmetirom including biomarkers. | Percentage | Limited from 0 to 100% | N/A |
| **Res_6.6** | `ongoing_annual_prop_fibro_res` | The percentage of annual assessments for Resmetirom including FibroScan. | Percentage | Limited from 0 to 100% | N/A |







##
